### ISSUE TITLE
Revise tutorial

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#569]
**Requirements:**
- #516 
- #573 
- #575 

**Tasks:**
- [x] update terminology 
-- Depends on #516
- [x] make sure it uses new user dict functionality; see docstring of StateDict() in https://github.com/AutoResearch/autora-core/blob/main/src/autora/state.py 
-- Depends on #575
- [x] explain why theorist does have a different decorator and wrapper "estimator_on_state" (for theorist we are using sklearn interface; this is different from the interface we use for experiment runners and experimentalists; thus you have to wrap theorists in a different way)
- [x] mention that theorists return sometimes lists and sometimes models (make clear what happens when; related to 
https://github.com/orgs/AutoResearch/discussions/543) [this issue should be covered. Theorists can return both a singular model or a list of models; both are used to update the list of models in the state.
- [x] There are some tutorials that aren't relevant anymore, such as. Would be necessary to remove the ones out of date.

**Comment by musslick** [comment]
depends on terminology #516

**Comment by chadcwilliams** [comment]
I am not certain how to implement the last three items for the tutorial (either I don't know what it means or else I don't know the explanation). I will bring this up in the next maintenance meeting.

**Comment by chadcwilliams** [comment]
Notes for Chad:

**User dict functionality**: Adding custom fields to the State (new state method)

**Explain why the theorists doesn't have the decorator**: b/c we use inherit scikit-learn interface rather than our custom interfaces w/ experimentalists and experiment runners (this is also for the wrapper) - i.e., why on_state vs estimator_on_state

**Theorists: sometimes lists and sometimes models**: If your delta object has one model return it, if it returns multiple models, make it a list.

**Comment by chadcwilliams** [comment]
All tasks completed
