### ISSUE TITLE
Restructure Documentation

### ISSUE THREAD

**Issue by musslick** [AutoResearch/autora#598]
Think about how to restructure the documentation page so that it "reads like a book", or at least that there is a curriculum. 

**Todo:**

- [x] Restructure as follows: @hollandjg 
- [x] remove "Core" level and move "States" and "Variables" up in the hierarchy of the documentation

**Tutorials:**
- [x] Components
- [x] Loop Constructs
- [x] Functional Workflow (link to the core tutorials) @chadcwilliams 
- [x] Customization
- [x] Closed-Loop Synthetic Discovery @musslick 
- [x] Closed-Loop Behavioral Experiments @younesStrittmatter 

**Examples:**
- [x] Equation Discovery in Psychology (Joshua & Chad) @chadcwilliams 
- [x] Evaluating Experimentation Strategies (Younes & Marina) @younesStrittmatter 
- [x] Closed-Loop Discovery of Learning Models (Daniel) @whyhardt

**Comment by musslick** [comment]
Recheck curriculum structure for tutorials

**Comment by chadcwilliams** [comment]
Delayed to march/april
